const { withDangerousMod } = require('expo/config-plugins');
const { readFileSync, writeFileSync } = require('fs');
const { join } = require('path');

/**
 * withModularHeaders — Expo config plugin (CNG-safe).
 *
 * @react-native-google-signin pulls in AppCheckCore, a Swift pod that depends on
 * GoogleUtilities + RecaptchaInterop. Those two don't ship module maps, so when
 * CocoaPods builds as static libraries (the Expo SDK 56 default — no
 * use_frameworks!), AppCheckCore can't `import` them and `pod install` dies with
 * "The following Swift pods cannot yet be integrated as static libraries". The
 * fix is to give those pods modular headers. expo-build-properties' `extraPods`
 * is INERT on the SDK 56 precompiled-modules Podfile template, so we patch the
 * generated Podfile directly, right after use_expo_modules! in the app target.
 * ios/ is regenerated by prebuild, so this runs every prebuild (not a hand-edit).
 *
 * Copied from chunky-crayon (the proven SDK 56 + google-signin fix).
 */
const MODULAR_HEADER_PODS = ['GoogleUtilities', 'RecaptchaInterop'];

const withModularHeaders = (config) =>
  withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfilePath = join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let contents = readFileSync(podfilePath, 'utf8');
      const marker = 'use_expo_modules!';
      if (
        contents.includes(marker) &&
        !contents.includes('# modular-headers')
      ) {
        const lines = MODULAR_HEADER_PODS.map(
          (name) => `  pod '${name}', :modular_headers => true`,
        ).join('\n');
        contents = contents.replace(
          marker,
          `${marker}\n\n  # modular-headers: AppCheckCore (via GoogleSignIn) needs these as modules\n${lines}`,
        );
        writeFileSync(podfilePath, contents);
      }
      return cfg;
    },
  ]);

module.exports = withModularHeaders;
